language: android

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - sys-img-armeabi-v7a-android-25

jdk:
- oraclejdk8

addons:
  sonarqube: true

before_install:
- chmod +x gradlew

script:
- ./gradlew build connectedCheck
- sonar-scanner -Dsonar.login=$SONAR_TOKEN

notifications:
  slack:
    secure: "DM7f9/+tG2pyaaijaPcdV/yqfeAnlNwusDbKuaD/WvTMBRUKWXAv/q0w+s2YUmUkoKVMQlBOqyvu5T62Jb8qGAXPP1PQnIMHHOl4IL6g70NBCtPzyzH97bl8F8Uk7fY1OYx1gmnCj2FYJ/B4wM1ZIR4nDChsoS+9BUpAlvO9OLlcC9MF/dWlpoddxktAl5+KR+Tg6AxqRMvdP5lEbiGb8GI44Z0jnkRAPRUsNDhnSZb+SgJzotLUOevTeROldGQxo0R4BiJxz5O/cyJ3bBr0ez6GdpQEiOY2Pod9RqQRRlXDMKCMHfh+8B30npGOrwSm7spCawVlu6lj4W3QzgfSiXdh5rNJ6BhjK5HXZ/+fm1OpgiB/sFwk0huYyyVkacQ+qr9Se7WsZbvZMvsHZeZfQweuFhSw0FlfkBaU6rE2frWD8JhujGM9HfdvFRmjNuHAL37cNlBS9qlV/MLpUTHIhFLStYhRdQoWuRoLiv0EjkUmo/B5zRhREIyDq+0Md1o0A6iFpE/T7qj535EkhOLwcLwbeKOT5KysOFYtNVnHBjpJ/P0nYP6V6YZ9y+tMSGmgCD2Tx1MIhpPPrFVYaKtwzbfbk8Es+XlzKh/OSPnhVgOgjPkewK7zN6PvyYAnzqx7282j1Ik91pTg6OuaOg2l9NN5o9uQh/I/27f1ZlHrs1Y="
